:PACKAGE:	- bsd:license:noinstall ast

LICENSE =	type=bsd

_BSDCOMPAT ==	1
__dead2 ==	;

:ALL:

cal :: cal.c -lcmd LICENSE='since=1989,author="Kim Letkeman"'

col :: col.c -lcmd LICENSE='since=1990,author="Michael Rendell"'

script :: script.c -lcmd LICENSE='since=1980'
