:PACKAGE:	- uwin

:ALL:

BINDIR = $(FUNDIR)

cv::		cv.sh
dirs::		dirs.sh
emacs_keybind::	emacs_keybind.sh
getopt::	getopt.sh
keybind::	keybind.sh
popd:LINK:	dirs
pushd:LINK:	dirs
title::		title.sh
vi_keybind::	vi_keybind.sh
winpath::	winpath.sh
