#! /bin/sh
#
# make-Rproto -- script for creating an R.proto file
#
# Copyright (C) 2006
# Free Software Foundation, Inc.
#      Written by Werner Lemberg <wl@gnu.org>
#
# This file is part of groff.
#
# groff is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2, or (at your option) any later
# version.
#
# groff is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with groff; see the file COPYING.  If not, write to the Free Software
# Foundation, 51 Franklin St - Fifth Floor, Boston, MA 02110-1301, USA.

#
# usage:
#
#   make-Rproto R.proto.in < uniuni.cpp > R.proto
#
# `R.proto.in' contains the device specific part of the R.proto file; it
# should end with a line containing the word `charset'.
#
# `uniuni.cpp' is located in directory `src/libs/libgroff'.

prog="$0"

if test $# -ne 1; then
  echo "usage: $0 R.proto.in < uniuni.cpp > R.proto"
  exit 1
fi

# Emit preamble.
cat "$1"

# Extract composite characters.
grep '^  { ".*", ".*_.*" },' \
| sed 's/  { "\(.*\)", ".\(.*\)" },/u\2	24	0	0x\1/'

# EOF
