BUILTINS =
CC = cc
CFLAGS = -O
DESTDIR = /v

%.o: %.c
	$CC -c $CFLAGS $stem.c

lex: lmain.o y.tab.o sub1.o sub2.o header.o
	$CC $prereq -o $target

smallex:
	cc -DSMALL lmain.c y.tab.c sub1.c sub2.c header.c -o smallex

y.tab.c: parser.y
	yacc parser.y
lmain.o: lmain.c ldefs.c once.c
	$CC -c $CFLAGS -DNCFORM='"/v/lib/lex.ncform"' lmain.c
sub1.o: sub1.c ldefs.c
	$CC -c $CFLAGS sub1.c
sub2.o: sub2.c ldefs.c
	$CC -c $CFLAGS sub2.c
header.o: header.c ldefs.c
	$CC -c $CFLAGS header.c

install: lex
	strip lex
	mv lex $DESTDIR/bin
	cp ncform $DESTDIR/lib/lex.ncform

clean:
	rm -f *.o lex y.tab.c
