strs==_s1
_num_struct==_nums
_back_tab==_cbt
_columns==_cols
_bool_struct==_bools
_auto_left_margin==_bw
SGTTY==struct termios 

tic::	tic.1 tic_captab.c tic_error.c tic_hash.c tic_main.c tic_parse.c \
	tic_read.c tic_scan.c -lcurses

:: terminfo.src
