//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by testcpl.rc
//
#define IDS_STRING1                     1
#define IDS_STRING2                     2
#define IDC_BUTTON_CLIENT_INSTALL_WIZARD 101
#define IDD_PROPPAGE_UMS                106
#define IDD_PROPPAGE_TELNET             107
#define IDD_PROPPAGE_UWINCLIENT         109
#define IDD_DIALOG_UCSINSTALL           135
#define IDD_DIALOG1                     139
#define IDI_ICON2                       141
#define IDD_DIALOG_MSG                  143
#define IDD_DIALOG_SHM                  144
#define IDD_DIALOG_SEM                  145
#define IDD_DIALOG_CONSOLE              146
#define IDD_PROPPAGE_SYSTEM             148
#define IDC_CHECK_FB                    149
#define IDD_DIALOG_RESOURCE             150
#define IDC_CHECK_FR                    151
#define IDD_DIALOG_PREVIEW              152
#define IDD_PROPPAGE_INETD              153
#define IDD_DIALOG_CONFIGUREDAEMON      159
#define IDD_PROPPAGE_GENERAL            160
#define IDD_DIALOG_INETDCONF_JUNK       161
#define IDD_DIALOG_COMMERCIALINFO       162
#define IDD_DIALOG_MISC                 173
#define IDC_CHECK_FG                    552
#define IDC_CHECK_FI                    553
#define IDC_CHECK_BR                    554
#define IDC_CHECK_BG                    555
#define IDC_CHECK_BI                    556
#define IDC_CHECK_BB                    557
#define IDC_BUTTON_PREVIEW              558
#define IDC_EDIT_TELNET_PORT            1000
#define IDC_EDIT_TELNET_MAXCONNS        1001
#define IDC_EDIT_UMS_SERVICE_NAME       1002
#define IDC_EDIT_UMS_STATE              1003
#define IDC_LIST_CLIENTLIST             1004
#define IDC_EDIT_UMS_ACCEPTED           1004
#define IDC_EDIT_CLIENT_DEPENDENCIES    1005
#define IDC_COMBO_UMS_STARTUP           1006
#define IDC_EDIT_UMS_DEPENDENCIES       1007
#define IDC_RADIO_CLIENT_DELETE         1007
#define IDC_EDIT_CLIENT_SERVICE         1008
#define IDC_RADIO_UMS_INSTALL           1009
#define IDC_EDIT_CLIENT_ACCEPTED_CONTROLS 1009
#define IDC_CHECK_SETUID                1010
#define IDC_EDIT_TELNET_SERVICE_NAME    1011
#define IDC_RADIO_UMS_DELETE            1012
#define IDC_RADIO_UMS_START             1013
#define IDC_RADIO_UMS_STOP              1014
#define IDC_EDIT_TELNET_STATE           1015
#define IDC_CHECK_ENUMERATE             1015
#define IDC_EDIT_TELNET_ACCEPTED        1016
#define IDC_CHECK_REUSE                 1016
#define IDC_EDIT_TELNET_DEPENDECIES     1017
#define IDC_COMBO_TELNET_STARTUP        1018
#define IDC_RADIO_TELNET_INSTALL        1019
#define IDC_RADIO_TELNET_DELETE         1020
#define IDC_RADIO_TELNET_START          1021
#define IDC_RADIO_TELNET_STOP           1022
#define IDC_TREE1                       1023
#define IDC_BUTTON_UCS_INSTALL          1024
#define IDC_EDIT_PASSWORD               1025
#define IDC_STATIC_CATEGORY             1028
#define IDC_COMBO_CATEGORY              1029
#define IDC_BUTTON_DEFAULT              1031
#define IDC_STATIC_MsgMaxIds            1035
#define IDC_EDIT_MsgMaxIds              1039
#define IDC_STATIC_MsgMaxQSize          1040
#define IDC_EDIT_MsgMaxQSize            1042
#define IDC_STATIC_MsgMaxSize           1043
#define IDC_EDIT_MsgMaxSize             1045
#define IDC_STATIC_MSG                  1046
#define IDC_STATIC_SHM                  1047
#define IDC_STATIC_ShmMaxIds            1048
#define IDC_STATIC_ShmMaxSegPerProc     1049
#define IDC_EDIT_ShmMaxIds              1050
#define IDC_EDIT_ShmMaxSegPerProc       1051
#define IDC_STATIC_ShmMaxSize           1052
#define IDC_EDIT_ShmMaxSize             1053
#define IDC_STATIC_ShmMinSize           1054
#define IDC_EDIT_ShmMinSize             1055
#define IDC_STATIC_SEM                  1056
#define IDC_STATIC_SemMaxIds            1057
#define IDC_EDIT_SemMaxIds              1058
#define IDC_STATIC_SemMaxInSys          1061
#define IDC_EDIT_SemMaxInSys            1062
#define IDC_STATIC_SemMaxOpsPerCall     1063
#define IDC_EDIT_SemMaxOpsPerCall       1064
#define IDC_STATIC_SemMaxSemPerId       1065
#define IDC_EDIT_SemMaxSemPerId         1066
#define IDC_STATIC_SemMaxVal            1067
#define IDC_EDIT_SemMaxVal              1068
#define IDC_STATIC_CONSOLE              1069
#define IDC_STATIC_TXTATTR              1070
#define IDC_RADIO_BOLD                  1071
#define IDC_RADIO_BLINK                 1072
#define IDC_RADIO_UNDERLINE             1073
#define IDC_RADIO_REVERSE               1074
#define IDC_STATIC_COLOR                1075
#define IDC_STATIC_COL_FG               1076
#define IDC_STATIC_COL_BG               1077
#define IDC_CHECK_COL_BLU               1078
#define IDC_CHECK_COL_BLU2              1079
#define IDC_CHECK_COL_RED               1081
#define IDC_CHECK_COL_GRN               1082
#define IDC_CHECK_COL_INTY              1083
#define IDC_CHECK_COL_RED2              1084
#define IDC_CHECK_COL_GRN2              1085
#define IDC_CHECK_COL_INTY2             1086
#define IDC_STATIC_PROFILE              1088
#define IDC_RADIO_ALLUSR                1089
#define IDC_RADIO_CURUSR                1090
#define IDC_STATIC_RESOURCE             1092
#define IDC_EDIT_FIFO                   1093
#define IDC_EDIT_FILE                   1094
#define IDC_EDIT_PROC                   1095
#define IDC_EDIT_SID                    1096
#define IDC_STATIC_FIFO                 1097
#define IDC_STATIC_FILE                 1098
#define IDC_STATIC_PROC                 1099
#define IDC_STATIC_SID                  1100
#define IDC_LIST_SERVICES               1105
#define IDC_STATIC_SERVICENAME          1106
#define IDC_EDIT_SERVICENAME            1107
#define IDC_STATIC_USER                 1114
#define IDC_STATIC_SERVERPATH           1116
#define IDC_EDIT_SERVERPATH             1117
#define IDC_STATIC_ARGUMENTS            1118
#define IDC_EDIT_ARGUMENTS              1119
#define IDC_BUTTON_APPLY                1120
#define IDC_STATIC_PROTOCOL             1122
#define IDC_RADIO_TCP                   1123
#define IDC_RADIO_UDP                   1124
#define IDC_COMBO_USER                  1125
#define IDC_BUTTON_BROWSE               1126
#define IDC_STATIC_SOCKETTYPE           1127
#define IDC_STATIC_FLAGS                1128
#define IDC_RADIO_STREAM                1129
#define IDC_RADIO_DGRAM                 1130
#define IDC_RADIO_NOWAIT                1131
#define IDC_RADIO_WAIT                  1132
#define IDC_BUTTON_REFRESH              1135
#define IDC_BUTTON_CONFIGURE            1136
#define IDC_BUTTON_ADD                  1137
#define IDC_BUTTON_DELETE               1138
#define IDC_BUTTON_ENABLE               1139
#define IDC_BUTTON_DISABLE              1140
#define IDC_STATIC_RELEASE              1141
#define IDC_STATIC_REGUSER              1142
#define IDC_COMBO_RELEASE               1143
#define IDC_STATIC_LOGLEVEL             1144
#define IDC_COMBO_LOGLEVEL              1145
#define IDC_STATIC_SETTINGS             1146
#define IDC_STATIC_LICENCEKEY           1147
#define IDC_EDIT_REGUSER                1149
#define IDC_EDIT_LICENCEKEY             1150
#define IDC_EDIT_OSVERSION              1152
#define IDC_EDIT_UWINVERSION            1153
#define IDC_STATIC_SYSTEMINFO           1154
#define IDC_STATIC_LICENCE              1155
#define IDC_STATIC_OSVERSION            1156
#define IDC_STATIC_UWINVERSION          1157
#define IDC_STATIC_JK_SERVNAME          1159
#define IDC_EDIT_JK_SERVNAME            1160
#define IDC_EDIT_JK_PORT                1161
#define IDC_STATIC_JK_PORT              1163
#define IDC_BUTTON_JK_DEFAULT           1164
#define IDC_CHECK_JK_ENABLE             1165
#define IDC_BUTTON_COMMERCIALINFO       1166
#define IDC_STATIC_WIPRO                1168
#define IDC_STATIC_GTL                  1169
#define IDC_STATIC_WIPRO2               1170
#define IDC_STATIC_WIPROURL             1174
#define IDC_STATIC_GTLURL               1175
#define IDC_STATIC_WIPROURL2            1176
#define IDC_STATIC_VENDORS              1179
#define IDC_STATIC_ONLINEINFO           1180
#define IDC_STATIC_MANPAGES             1181
#define IDC_STATIC_KNLGBASE             1182
#define IDC_STATIC_KNLGBASEURL          1183
#define IDC_STATIC_MANPAGESURL          1184
#define IDC_COMBO1                      1189
#define IDC_STATIC_MISC                 1192
#define IDC_CHECK_CASESENSITIVE         1193
#define IDC_CHECK_PASSFLAG              1194
#define IDC_CHECK_NOSHAMWOW         	1195

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1195
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
